name: Prose

on: [push, pull_request]

# This job installs dependencies, build the site, and pushes it to `gh-pages``
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install LaTeX
      run: |
        sudo apt-get update
        #LaTeX packages
        sudo apt-get install -y texlive-latex-extra
        sudo apt-get install -y texlive-xetex
        sudo apt-get install texlive-bibtex-extra biber
        sudo apt-get install -y texlive-lang-greek
        sudo apt-get install -y latexmk
        sudo apt-get install lmodern
        sudo apt-get install texlive-fonts-extra
    - name: Check LaTeX compiles
      run: |
        cd tex; xelatex -shell-escape main.tex
